# MMD 2024, Problem Sheet 2: Latent Factor Models

Group: Daniela Fichiu, Aaron Maekel, Manuel Senger

## Exercise 1

**Task:** Consider a web shop that sells furniture and uses a recommendation system. When a
new user creates an account and likes one product, he will be presented with similar
products on his next visit.

How can a competitor - in principle - try to steal the valuable data for recommendation
from this website? Does this work better when the web shop implemented a content-
based (CB) or a collaborative filtering (CF) system? What data would the competitor be able to
infer? Would this technique have an impact on the recommendation system, i.e., would
this attack create a bias on the data? Why is this attack probably not viable in any
case?

**Solution:** By liking a product and receiving a list of similar products, the competitor can infer which products are similar to the one liked. This works better when the shop implements a CB approach. On one hand, the cold-start problem specific to CF disappears. On the other hand, user-user CF is based on matching a specific user to all the others. That is, a CF approach would mean the competitor would have to create specific users to receive recommendations for this specific user. The competitor would be able to infer which products are similar to the liked product. While a slight bias might be thinkable in the CF case, irrespective of the recommendation approach, nothing would happen. In the CB setting this is due to the features being hand-crafted. For the user-user CF setting, the competitor would have to create user vectors somewhat similar to the existing ones and additionally like items that the existing user would have never considered. The attack is not viable since it would require the creation of many user accounts which would like a single item or a very small set of items. This activity, however, would most certainly be detected by the server hosting the web shop.

## Exercise 2

The following table shows a utility matrix with ratings on a 1-5 star scale of eight items, a through h, by three users, A, B and C.

|   | a | b | c | d | e | f | g | h |
|---|---|---|---|---|---|---|---|---|
| A | 4 | 5 |   | 5 | 1 |   | 3 | 2 |
| B |   | 3 | 4 | 3 | 1 | 2 | 1 |   |
| C | 2 |   | 1 | 3 |   | 4 | 5 | 3 |

Perform the following tasks. Submit only your results (no code, even if you have used any).

a) **Task:** Treating each blank entry in the utility matrix as 0, compute the cosine distance between each pair of users.

**Solution:**
The cosine distance is defined as $1 -$ the cosine similarity. Therefore, we first compute the dot products between the vectors and their norms, and then the cosine similarites.

Norms:
- $\Vert A \Vert_2 = (4^2 + 5^2 + 5^2 + 1 + 3^2 + 2^2)^{1/2} \approx 9$
- $\Vert B \Vert_2 = (3^2 + 4^2 + 3^2 + 1 + 2^2 + 1)^{1/2} \approx 6$
- $\Vert C \Vert_2 = (2^2 + 1 + 3^2 + 4^2 + 5^2 + 3^2)^{1/2} = 8$

Dot products:
- $ A \cdot B = (4 \cdot 0 + 5 \cdot 3 + 0 \cdot 4 + 5 \cdot 3 + 1 \cdot 1 + 0 \cdot 2 + 3 \cdot 1 + 2 \cdot 0) = 34$
- $ A \cdot C = (4 \cdot 2 + 5 \cdot 0 + 0 \cdot 1 + 5 \cdot 3 + 1 \cdot 0 + 0 \cdot 4 + 3 \cdot 5 + 2 \cdot 3) = 44$
- $ B \cdot C = (0 \cdot 2 + 3 \cdot 0 + 4 \cdot 1 + 3 \cdot 3 + 1 \cdot 0 + 2 \cdot 4 + 1 \cdot 5 + 0 \cdot 3) = 26$

Cosine similarities:
- $\cos_\text{sim}(A, B) = A \cdot B / \Vert A \Vert_2 \Vert B \Vert_2 = 34 / 9 \cdot 6 \approx 0.6$
- $\cos_\text{sim}(A, C) = A \cdot C / \Vert A \Vert_2 \Vert C \Vert_2 = 44 / 9 \cdot 8 \approx 0.6$
- $\cos_\text{sim}(B, C) = B \cdot C / \Vert B \Vert_2 \Vert C \Vert_2 = 26 / 6 \cdot 8 \approx 0.55$

Cosiene distances:
- $\cos_\text{dist}(A, B) = 1 - \cos_\text{sim}(A, B) \approx 1 - 0.6 \approx 0.4$
- $\cos_\text{dist}(A, C) = 1 - \cos_\text{sim}(A, C) \approx 1 - 0.6 \approx 0.4$
- $\cos_\text{dist}(B, C) = 1 - \cos_\text{sim}(B, C) \approx 1 - 0.55 \approx 0.45$


b) **Task:** Treating ratings of 3, 4, and 5 as 1 and 1, 2, and blank as 0, compute the cosine distance between each pair of users. Compare these results to those obtain in Part a).

**Solution:** Converting 3 and 4 to 1 and 5 to 2, we obtain the following utility matrix:


|   | a | b | c | d | e | f | g | h |
|---|---|---|---|---|---|---|---|---|
| A | 1 | 2 |   | 2 | 1 |   | 1 | 2 |
| B |   | 1 | 1 | 1 | 1 | 2 | 1 |   |
| C | 2 |   | 1 | 1 |   | 1 | 2 | 1 |

For the obtained utility matrix, we repeat the steps from Part a).

Norms:
- $\Vert A \Vert_2 = (1^2 + 2^2 + 2^2 + 1 + 1^2 + 2^2)^{1/2} \approx 4$
- $\Vert B \Vert_2 = (1^2 + 1^2 + 1^2 + 1 + 2^2 + 1)^{1/2} \approx 3$
- $\Vert C \Vert_2 = (2^2 + 1 + 1^2 + 1^2 + 2^2 + 1^2)^{1/2} \approx 3.5$

Dot products:
- $ A \cdot B = (1 \cdot 0 + 2 \cdot 1 + 0 \cdot 1 + 2 \cdot 1 + 1 \cdot 1 + 0 \cdot 2 + 1 \cdot 1 + 2 \cdot 0) = 6$
- $ A \cdot C = (1 \cdot 2 + 2 \cdot 0 + 0 \cdot 1 + 2 \cdot 1 + 1 \cdot 0 + 0 \cdot 1 + 1 \cdot 2 + 2 \cdot 1) = 8$
- $ B \cdot C = (0 \cdot 2 + 1 \cdot 0 + 1 \cdot 1 + 1 \cdot 1 + 1 \cdot 0 + 2 \cdot 1 + 1 \cdot 2 + 0 \cdot 1) = 6$

Cosine similarities:
- $\cos_\text{sim}(A, B) = A \cdot B / \Vert A \Vert_2 \Vert B \Vert_2 = 6 / 4 \cdot 3 \approx 0.5$
- $\cos_\text{sim}(A, C) = A \cdot C / \Vert A \Vert_2 \Vert C \Vert_2 = 8 / 4 \cdot 3.5 \approx 0.57$
- $\cos_\text{sim}(B, C) = B \cdot C / \Vert B \Vert_2 \Vert C \Vert_2 = 6 / 3 \cdot 3.5 \approx 0.57$

Cosine distances:
- $\cos_\text{dist}(A, B) = 1 - \cos_\text{sim}(A, B) \approx 1 - 0.5 \approx 0.5$
- $\cos_\text{dist}(A, C) = 1 - \cos_\text{sim}(A, C) \approx 1 - 0.57 \approx 0.43$
- $\cos_\text{dist}(B, C) = 1 - \cos_\text{sim}(B, C) \approx 1 - 0.57 \approx 0.43$

The results obtained are similar to those from Part a). The biggest changes are in the cosine distances of A. This is due to the fact that from the 6 non-blank entries of A (of which two were 5), four got changed.

c) **Task:** Normalize the matrix by substracting from each non-blank entry the average value for its user. Then compute the cosine distance between each pair of users (blank entries are treated as 0).

**Solution:** We compute the averages only over the existing values:

Averages:
- $A = \frac{(4 + 5 + 5 + 1 + 3 + 2)}{6} \approx 3.3$
- $B = \frac{(3 + 4 + 3 + 1 + 2 + 1)}{6} \approx 2.3$
- $C = \frac{(2 + 1 + 3 + 4 + 5 + 3)}{6} = 3$

The normalized matrix has is then given by


|   | a | b | c | d | e | f | g | h |
|---|---|---|---|---|---|---|---|---|
| A | 0.7 | 1.7 |   | 1.7 | -2.3 |   | -0.3 | -1.3 |
| B |   | 0.7 | 1.7 | 0.7 | -1.3 | -0.3 | -1.3 |   |
| C | -1 |   | -2 | 0 |   | 1 | 2 | 0 |


Norms:
- $\Vert A \Vert_2 \approx 3.6$
- $\Vert B \Vert_2 \approx 2.7$
- $\Vert C \Vert_2 \approx 3.1$

Dot products:
- $ A \cdot B \approx 5.7$
- $ A \cdot C \approx -1.29$
- $ B \cdot C \approx -6.3$

Cosine similarities:
- $\cos_\text{sim}(A, B) = A \cdot B / \Vert A \Vert_2 \Vert B \Vert_2 = 5.7 / (3.6 \cdot 2.7) \approx 0.5$
- $\cos_\text{sim}(A, C) = A \cdot C / \Vert A \Vert_2 \Vert C \Vert_2 = -1.29 / (3.6 \cdot 3.1) \approx -0.1$
- $\cos_\text{sim}(B, C) = B \cdot C / \Vert B \Vert_2 \Vert C \Vert_2 = -6.3 / (2.7 \cdot 3.1) \approx -0.7$

Cosine distances:
- $\cos_\text{dist}(A, B) = 1 - \cos_\text{sim}(A, B) \approx 1 - 0.5 \approx 0.5$
- $\cos_\text{dist}(A, C) = 1 - \cos_\text{sim}(A, C) \approx 1 + 0.1 \approx 1.1$
- $\cos_\text{dist}(B, C) = 1 - \cos_\text{sim}(B, C) \approx 1 + 0.7 \approx 1.7$

d) **Task:** Compute the Pearson correlation coefficient between each pair of users as defined in Lecture 1 (slide "From Cosine to Pearson"). Compare these results to those obtained in Part c) and state your conclusions.

**Solution:** The only difference between the Pearson coefficient and the cosine similarites computed in Part c) is that the Pearson coefficient computes the norm-like denominators over the commonly rated items.

Denominators for the cosine similarity between:
- $A$ and $B$: $d_{AB} \approx 7$ (over items b, d, e, g)
- $A$ and $C$: $d_{AC} \approx 5$ (over items a, d, g, h)
- $B$ and $C$: $d_{BC} \approx 7$ (over items c, d, f, g)

Cosine similarities:
- $\cos_\text{sim}(A, B) = A \cdot B / d_{AB} \approx 5.7 / 7 \approx 0.8$
- $\cos_\text{sim}(A, C) = A \cdot C / d_{AC} \approx -1.29 / 5 \approx -0.2$
- $\cos_\text{sim}(B, C) = B \cdot C / d_{BC} \approx -6.3 / 7 \approx -0.9$

Cosine distances:
- $\cos_\text{dist}(A, B) = 1 - \cos_\text{sim}(A, B) \approx 1 - 0.8 \approx 0.2$
- $\cos_\text{dist}(A, C) = 1 - \cos_\text{sim}(A, C) \approx 1 + 0.2 \approx 1.2$
- $\cos_\text{dist}(B, C) = 1 - \cos_\text{sim}(B, C) \approx 1 + 0.9 \approx 1.9$

TODO: Write comparison.

## Exercise 3

Consider the function `uv_factorization_vec_no_reg` from `rec_sys/lf_algorithms.py` and the functions utilized there. Perform the following tasks:

a) **Task:** Implement the function `uv_factorization_vec_reg` (along with any necessary helper or sub-functions) which executes the SDG using a loss function with the regularization terms discussed in the lecture. Use one common regularization parameter for both matrices. Test your implementation using the settings from `rec_sys/config.py` (you might need to adjust  some hyperparameters). Then, use the function `show_metrics_and_examples` to compare the convergence and the accuracy of your function against the non-regularizd version of SGD from the original (i.e., repository) code.

**Solution:** See `uv_factorization_vec_reg` in `rec_sys/lf_algorithms.py`.

b) **Solution:** The grid search was done in 'lf_algorithms_grid_search.py' , we tried the learning rates  [0.1 , 0.05, 0.01, 0.005, 0.001] and the regularization parameters [0.0001,0.0005, 0.001, 0.005 ,0.01  ].
We compared them after the MSE over all test data.

|reg\lr  | 0.1 | 0.05 | 0.01 | 0.005 | 0.001 |
|--------|-----|------|------|-------|-------| 
| 0.0001 |3.08 | 0.98 | 1.12 | 1.21  | 1.46  | 
| 0.0005 |1.65 | 0.96 | 1.00 | 1.03  | 1.34  | 
| 0.001  |1.31 | 0.95 | 0.98 | 0.99  | 1.26  | 
| 0.005  |1.46 | 1.31 | 1.22 | 1.14  | 1.26  | 
| 0.01   |2.57 | 2.43 | 1.98 | 1.64  | 1.38  | 

The winner was lr= 0.05 , reg = 0.001. We compared this to the original Algorithm, again the criterium was the MSE on the test data set:

Original Algorithm:  1.1605393

fixed_lr and with reg:    1.0945647






## Exercise 4



# a)

If the maximum Degree is N for one variable, than it can be in the polynomial part as {0,1,...,N} variants.
THis means that there are (N_x + 1 ) * (N_Y + 1)  * ( N_z + 1) possible  combinations of these variables resulting in the same amount of coefficients.

Version 1: Shape: [t,4] (x,y,z, and coeff) (dependent on t)

Version 2:This would result in an three dimensional matrix having the shape [((N_x + 1 ), (N_Y + 1),( N_z + 1))] (independent of t )

we tried implementing both versions, as we were unsure how to proceed, in both cases problems arised.

# b)

In [6]:
#import rec_sys.jax_intro as jax_intro
import jax.numpy as jnp
import jax
import time
import random
rnd_seed = int(time.time())
rnd_key = jax.random.PRNGKey(rnd_seed)

Version 1:

In [9]:


def gen_polynomial(Nx,Ny,Nz,t):
    
    max_arr = [Nx,Ny,Nz]
    
    
    indx = jax.random.randint(  rnd_key, (t,3), jnp.zeros((t,3)),
                                jnp.reshape(jnp.repeat(jnp.array([Nx+1,Ny+1,Nz+1]),repeats=t,axis=0 ),
                                newshape=(3,t)).T)
    
    
    for i in range(3):
        
        if max(indx[:,i])< max_arr[i] :
            rnd_indx = random.randint(0, t-1)
            indx = indx.at[rnd_indx,i].set(max_arr[i]) 
    LIM = 5
    rnd_coeff = jax.random.randint(  rnd_key, (t,1), -LIM * jnp.ones((t,1)),
                                    LIM * jnp.ones((t,1))
                                     )
    coeff_mat = jnp.hstack([indx,rnd_coeff])
    return(coeff_mat)



def f(x,y,z,polym):
    res = jnp.zeros(x.shape[0])
    for i in range(polym.shape[0]):
        res += polym[i,3] * jnp.power(x,polym[i,0])* jnp.power(y,polym[i,1])* jnp.power(z,polym[i,2])
    return(res)




def generate_noisy_set(N,coeff_mat):
    noise_frac, rnd_seed =  0.25, int(time.time())
    x,y,z = jnp.linspace(-3, 3,N),jnp.linspace(-3, 3,N),jnp.linspace(-3, 3,N)
    res_pure = f(x,y,z,coeff_mat)
    # Add some noise to data
    rnd_key = jax.random.PRNGKey(rnd_seed)
    y_with_noise = res_pure + res_pure * noise_frac * jax.random.normal(rnd_key, (N,))
    return x,y,z,y_with_noise

polym = gen_polynomial(3,1,2,5)
print("Example polynomial based on Polynomial configuration 2")
print(polym)
#print(generate_noisy_set(10,polym) )

#print(generate_noisy_set(2,jnp.array([[1,1,1,1],[0,0,0,0]])) )



Example polynomial based on Polynomial configuration 2
[[ 0  1  0  0]
 [ 3  0  2  2]
 [ 0  1  2  1]
 [ 1  0  0 -4]
 [ 2  1  2 -5]]


Version 2:

In [10]:
def gen_polynomial2(Nx,Ny,Nz,t):
    LIM = 3
    rnd_seed = int(time.time())
    max_arr = [Nx,Ny,Nz]

    coeff_mat = jnp.zeros((Nx+1,Ny+1,Nz+1))
    for _ in range(t):
        rnd_coeff = random.randint(-LIM,LIM)
        while rnd_coeff ==0:
            rnd_coeff = random.randint(-LIM,LIM)
        coeff_mat = coeff_mat.at[random.randint(0,Nx),random.randint(0,Ny),random.randint(0,Nz)].set(rnd_coeff) 


    while not jnp.any(coeff_mat[-1,:,:]):
        coeff_mat = jnp.roll(coeff_mat,1,0)
    while not jnp.any(coeff_mat[:,-1,:]):
        coeff_mat = jnp.roll(coeff_mat,1,1)
    while not jnp.any(coeff_mat[...,-1]):
        coeff_mat = jnp.roll(coeff_mat,1,2)
    return coeff_mat


def f2(x,y,z,polym):
    res = jnp.zeros(x.shape[0])
    for i in range(polym.shape[0]):
        for j in range(polym.shape[1]):
            for k in range(polym.shape[2]):
                res += polym[i,j,k] * jnp.power(x,i)* jnp.power(y,j)* jnp.power(z,k)
    return(res)

def generate_noisy_set2(N,coeff_mat):
    noise_frac, rnd_seed =  0.25, int(time.time())
    x,y,z = jnp.linspace(-3, 3,N),jnp.linspace(-3, 3,N),jnp.linspace(-3, 3,N)
    res_pure = f2(x,y,z,coeff_mat)
    # Add some noise to data

    res_with_noise = res_pure + res_pure * noise_frac * jax.random.normal(rnd_key, (N,))
    return x,y,z,res_with_noise

polym = gen_polynomial2(3,1,2,5)
print("Example polynomial based on Polynomial configuration 2")
print(polym)

Example polynomial based on Polynomial configuration 2
[[[ 0.  0.  0.]
  [ 0.  0.  3.]]

 [[ 0.  0.  0.]
  [-1.  0.  0.]]

 [[ 0. -1.  0.]
  [ 0. -1.  0.]]

 [[ 0.  0.  0.]
  [ 0.  1.  0.]]]


# c)

Version 1:


In [13]:
 
#polynomials:
polym1 = gen_polynomial(2,4,6,12)
polym2 = gen_polynomial(3,1,2,5)

def SGD(polynomial,Nx,Ny,Nz,t):

    # %% Run the SG loop
    num_epochs = 1
    learning_rate = 0.05
    train_set_size = 10000
    train_ds  = jnp.asarray(generate_noisy_set(train_set_size ,polynomial))
    
    param_w = gen_polynomial(Nx,Ny,Nz,t).astype(float)  # Initial guess for the parameter

    # %% Define a simple loss function and its gradient
    def loss(param_w, data):
        # return  jnp.sum((data[:,1] - f(data[:,0], param_w))**2)
        res = f(data[0],data[1],data[2], param_w)

        return jnp.log(jnp.sum((data[3] - res) ** 2)) 


    # Using JAX automatic differentiation - autograd
    grad_loss = jax.grad(loss)#,allow_int=True)

    num_points_per_batch = train_set_size // 5
    print("\n===== Running Stochastic Gradient Descent =====")
    for epoch in range(num_epochs):
        # Get points for the current batch
        for i in range(0, train_set_size, num_points_per_batch):
            batch = train_ds[:,i:i + num_points_per_batch]
            grad = grad_loss(param_w, batch)
            param_w = param_w - learning_rate * grad

        print(f"Epoch {epoch}: param_w={param_w}, grad={grad}, loss={loss(param_w, train_ds)}")

    print(polynomial)
    print(param_w)
SGD(polym2,3,1 ,2,5)



===== Running Stochastic Gradient Descent =====
Epoch 0: param_w=[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]], grad=[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]], loss=nan
[[ 0  1  0  0]
 [ 3  0  2  2]
 [ 0  1  2  1]
 [ 1  0  0 -4]
 [ 2  1  2 -5]]
[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]


Parts of the gradient correlating for the x y and z data became NaN, thus destroying the whole process.

Version 2:

In [12]:
 
#polynomials:
polym1 = gen_polynomial2(2,4,6,12)
polym2 = gen_polynomial2(3,1,2,5)

print(polym2)
def SGD(polynomial,Nx,Ny,Nz,t):

    # %% Run the SG loop
    num_epochs = 50
    learning_rate = 0.05
    train_set_size = 10000
    train_ds  = jnp.asarray(generate_noisy_set2(train_set_size ,polynomial))
    
    param_w = jnp.zeros((Nx+1,Ny+1,Nz+1)) #gen_polynomial2(Nx,Ny,Nz,t).astype(float)  # Initial guess for the parameter

    # %% Define a simple loss function and its gradient
    def loss(param_w, data):
        # return  jnp.sum((data[:,1] - f(data[:,0], param_w))**2)
        res = f2(data[0],data[1],data[2], param_w)
      
        return jnp.log(jnp.sum((data[3] - res) ** 2)) 

    # Using JAX automatic differentiation - autograd
    grad_loss = jax.grad(loss)

    num_points_per_batch = train_set_size // 5
    print("\n===== Running Stochastic Gradient Descent =====")
    for epoch in range(num_epochs):
        # Get points for the current batch
        for i in range(0, train_set_size, num_points_per_batch):
            batch = train_ds[:,i:i + num_points_per_batch]
            grad = grad_loss(param_w, batch)
            param_w = param_w - learning_rate * grad

        print(f"Epoch {epoch}:  loss={loss(param_w, train_ds)}")
    print(polynomial)
    print(param_w)
SGD(polym2,3,1,2,5)


[[[ 0.  0.  0.]
  [ 0. -2.  0.]]

 [[ 0.  0. -2.]
  [ 0. -1.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0. -3.]]]

===== Running Stochastic Gradient Descent =====
Epoch 0:  loss=22.013757705688477
Epoch 1:  loss=21.905046463012695
Epoch 2:  loss=21.78440284729004
Epoch 3:  loss=21.647014617919922
Epoch 4:  loss=21.48792839050293
Epoch 5:  loss=21.303478240966797
Epoch 6:  loss=21.08243179321289
Epoch 7:  loss=20.8350887298584
Epoch 8:  loss=20.543737411499023
Epoch 9:  loss=20.33692741394043
Epoch 10:  loss=20.09905433654785
Epoch 11:  loss=19.927234649658203
Epoch 12:  loss=19.749502182006836
Epoch 13:  loss=19.660423278808594
Epoch 14:  loss=19.583248138427734
Epoch 15:  loss=19.563278198242188
Epoch 16:  loss=19.52655029296875
Epoch 17:  loss=19.523616790771484
Epoch 18:  loss=19.48839569091797
Epoch 19:  loss=19.493303298950195
Epoch 20:  loss=19.469438552856445
Epoch 21:  loss=19.472843170166016
Epoch 22:  loss=19.438831329345703
Epoch 23:  loss=19.4359531402

it manages to get approximate some cells, but because every variable combination is possible, does this show a very slow convergence

# Exercise 5

There are different options for tracking memory allocation in JAX. Firstly there is the built-in JAX.profiler, which includes the method device-memory-profile. This captures a JAX device memory profile as pprof-format protocol buffer, which you can read with the pprof-tool. As far as i understand this that only works with go. I also looked at jax-smi, which is supposed to be a "a tool for real-time inspection of the memory usage of a JAX process". This also returns a pprof file. Reading this file takes me some time and im trying different solutions on windows.

There are different options for tracking memory allocation in JAX. Firstly there is the built-in JAX.profiler, which includes the method device-memory-profile. This captures a JAX device memory profile as pprof-format protocol buffer, which you can read with the pprof-tool. As far as i understand this that only works with go. I also looked at jax-smi, which is supposed to be a "a tool for real-time inspection of the memory usage of a JAX process". This also returns a pprof file. Reading this file takes me some time and im trying different solutions on windows.

In [1]:
pip install jax-smi

Note: you may need to restart the kernel to use updated packages.


In [2]:
import dataclasses
import jax
import jax.numpy as jnp
import tensorflow_datasets as tfds
from jax_smi import initialise_tracking
import pandas as pd
import pstats
import jax.profiler
from datetime import datetime
import tensorboard


In [3]:
# Create a test matrix u and v to test memory allocation using jax-smi
key = jax.random.PRNGKey(0)
size = 1000
num_choices = 50
mat_u = jax.random.normal(jax.random.PRNGKey(0), (1000, 1000))  # as initialized in init_latent_factors
mat_v = jax.random.normal(jax.random.PRNGKey(1), (1000, 1000))
rows = jax.random.choice(key, jnp.arange(size), (num_choices,), replace=False)
columns = jax.random.choice(key, jnp.arange(size), (num_choices,), replace=False)

In [4]:
@jax.jit  # Comment out for single-step debugging
def mse_loss_one_batch_test(mat_u, mat_v, rows, columns):
    # Original code in question
    jax_smi.initialise_tracking()
    estimator = -(mat_u @ mat_v)[(rows, columns)]

    return estimator

mse_loss_one_batch_test(mat_u, mat_v, rows, columns)


NameError: name 'jax_smi' is not defined

# Exercise 5

There are different options for tracking memory allocation in JAX. Firstly there is the built-in JAX.profiler, which includes the method device-memory-profile. This captures a JAX device memory profile as pprof-format protocol buffer, which you can read with the pprof-tool. As far as i understand this that only works with go. I also looked at jax-smi, which is supposed to be a "a tool for real-time inspection of the memory usage of a JAX process". This also returns a pprof file. Reading this file takes me some time and im trying different solutions on windows.

In [23]:
pip install jax-smi

In [40]:
pip install snakeviz

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.7/283.7 kB 7.5 MB/s eta 0:00:00


In [37]:
import dataclasses
import jax
import jax.numpy as jnp
import tensorflow_datasets as tfds
from jax_smi import initialise_tracking
import pandas as pd
import pstats
import jax.profiler
from datetime import datetime
import tensorboard


In [41]:
# Create a test matrix u and v to test memory allocation using jax-smi
key = jax.random.PRNGKey(0)
size = 1000
num_choices = 50
mat_u = jax.random.normal(jax.random.PRNGKey(0), (1000, 1000))  # as initialized in init_latent_factors
mat_v = jax.random.normal(jax.random.PRNGKey(1), (1000, 1000))
rows = jax.random.choice(key, jnp.arange(size), (num_choices,), replace=False)
columns = jax.random.choice(key, jnp.arange(size), (num_choices,), replace=False)

In [42]:
@jax.jit  # Comment out for single-step debugging
def mse_loss_one_batch_test(mat_u, mat_v, rows, columns):
    # Original code in question
    jax_smi.initialise_tracking()
    estimator = -(mat_u @ mat_v)[(rows, columns)]

    return estimator

mse_loss_one_batch_test(mat_u, mat_v, rows, columns)


Array([  2.2403035,   5.137396 , -18.212055 ,  29.806274 ,  -5.4359016,
        23.092825 ,   7.4908133, -33.361286 ,  10.951368 ,  -9.150698 ,
       -14.942288 , -26.868412 , -39.69823  ,  39.272816 ,   1.6286244,
        -5.6750965,  -7.0394726, -16.87818  ,  40.452354 ,  21.958443 ,
         3.4872444, -39.629883 , -11.130831 , -70.76534  ,  -8.12375  ,
         9.263904 ,   4.5230556,  33.51147  ,  15.698744 , -12.131374 ,
        23.615482 , -38.220226 , -12.183689 , -46.414795 , -56.122215 ,
         3.612556 ,  -8.421157 ,  -1.4403391, -22.431568 , -25.093353 ,
        40.38521  ,  13.682131 ,  13.957107 ,  13.326932 ,  79.68028  ,
       -26.777143 , -15.372421 ,  21.608826 ,  19.776518 ,   2.97534  ],      dtype=float32)

SyntaxError: invalid syntax (<ipython-input-39-082791cceb04>, line 1)

## Exercise 6


# a)
The rating of a professor should be divided into multiple categories ( makes a good lecture, is a good supervisor etc.), as tchey an differ a lot. This means, each time a user rates a lecture,seminar, thesis supervision, the rating should only affect the categories it fits best. ( having had a bad thesis supervision is not important for the quality of the lecture the professor will organize)

# b)

if the artworks are items, then there should be tags describing the essence of each artwork like {scary,nature,goofy}. These can be used to find out which genres the user prefers and are usable in content recommender systems.

A better focus than the artwork may be the artists themselves, If a user likes an artwork he will prefer other art made in the same style, thus being from the same artist, compared to different artwork which may have the same topics, but differ in style. Thus the algorithm should rather try to match user and artist compared to user and picture.


# c)
There is no user-item pairing, it is a user-user pairing. This changes the problem dramatically, as both users have to rate each other, thus a bidirectional pairing has to be done.

 Features could be superficial ( haircolor/weight etc.), personal information(age, religion, etc.) and tastes/dislikes (music genres, food etc.).   


Another difficulty is in the aggregation of non-superficial data, as it is hard to put into categories, but may be even the most important data of all.

# Exercise 7

## a)

**G (global effects)** will probably return a newly published and well rated movie - that is quite popular - as a recommendation. The R system (regional effects) would be more aligned with the users preferences in terms of genre, director, actors etc. These are more likely to align with the taste of the specific user.

The **L system (local effects)** would be the most personalized, as it would take into account the users previous ratings and preferences and compare them with other users. Depending on the size of the user cluster these can include more niche movies.

**The System R** probably produces the most niche and exotic items, as it can infer personalized, latent factors in user preferences. System L cann offer some niche recommendations and System G mostly sticks to widely popular items.

## b)

Depending on the size of the Dataset, System G would probably be the most vulnerable to this attack. Thats because it bases recommendations on global ratings and trends. So if a lot of user rate a movie with 5 stars, it will be recommended to a lot of other users, regardless of their preferences. In contrast, System L is the most robust against this manipulation. The fake accounts would mainly affect the reommendations of the fake accounts within the fake cluster, so their impact on the overall system is limited.

## c)
Both System G and System L fail for grey sheep, as they are based on global trends or user clusters. The grey sheep are users that do not fit into any cluster and have preferences that are not aligned with the global trends. System R is the only one that can recommend items to grey sheep, as it is based on the users preferences and not on global trends or user clusters and might align from time to time. Black sheep are very hard to capture and neither of the systems can reliable recommend items to them.    
